import random
from django.utils import timezone
from annotate_aggregate.models import Author, Book, Store, Publisher
from django.core.management.base import BaseCommand
from faker import Faker

fake = Faker()



            for publisher in Publisher.objects.all():
                for _ in range(int(num)):
                    Book.objects.bulk_create([Book(name=fake.sentence(),
                                                   price=random.uniform(29.99, 225.9),
                                                   pages=random.randint(50, 300),
                                                   rating=round(random.uniform(1, 5), 2),
                                                   pubdate=timezone.now(),
                                                   publisher=publisher)])

        tag_ids = list(Book.objects.values_list('id', flat=True))
        photo_ids = Author.objects.values_list('id', flat=True)
        tag_count = len(tag_ids)

        for author_id in photo_ids:
            books = []
            random.shuffle(books)

            rand_num_tags = random.randint(0, tag_count)
            photo_tags = tag_ids[:rand_num_tags]

            for book_id in photo_tags:
                # through is the table generated by django to link m2m between tag and photo
                book = Book.authors.through(book_id=book_id, author_id=author_id)
                books.append(book)

            Book.authors.through.objects.bulk_create(books, batch_size=7000)
