# Generated by Django 3.2.4 on 2021-07-22 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['-id']},
        ),
    ]
